import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Quote } from '../entities/quote.entity';
import { CreateQuoteDto } from './dto/create-quote.dto';
import { UpdateQuoteDto } from './dto/update-quote.dto';
import { User } from '../entities/user.entity';
import PDFDocument from 'pdfkit';

@Injectable()
export class QuotesService {
  constructor(
    @InjectRepository(Quote)
    private quotesRepository: Repository<Quote>,
    @InjectRepository(User)
    private usersRepository: Repository<User>,
  ) {}

  async create(userId: string, createQuoteDto: CreateQuoteDto): Promise<Quote> {
    const user = await this.usersRepository.findOne({ where: { id: userId } });
    if (!user) {
      throw new NotFoundException('User not found');
    }

    const quote = this.quotesRepository.create({
      ...createQuoteDto,
      userId,
      status: 'requested',
    });

    return this.quotesRepository.save(quote);
  }

  async findAll(userId: string): Promise<Quote[]> {
    return this.quotesRepository.find({
      where: { userId },
      order: { createdAt: 'DESC' },
    });
  }

  async findOne(userId: string, id: string): Promise<Quote> {
    const quote = await this.quotesRepository.findOne({
      where: { id, userId },
    });

    if (!quote) {
      throw new NotFoundException('Quote not found');
    }

    return quote;
  }

  async update(
    userId: string,
    id: string,
    updateQuoteDto: UpdateQuoteDto,
  ): Promise<Quote> {
    const quote = await this.findOne(userId, id);
    Object.assign(quote, updateQuoteDto);
    return this.quotesRepository.save(quote);
  }

  async updateStatus(
    userId: string,
    id: string,
    status: string,
  ): Promise<Quote> {
    const quote = await this.findOne(userId, id);
    quote.status = status;
    return this.quotesRepository.save(quote);
  }

  async delete(userId: string, id: string): Promise<void> {
    const quote = await this.findOne(userId, id);
    await this.quotesRepository.remove(quote);
  }

  async downloadProposal(userId: string, id: string): Promise<Buffer> {
    const quote = await this.findOne(userId, id);

    if (!quote.proposal) {
      throw new NotFoundException('Proposal not yet generated for this quote');
    }

    const doc = new PDFDocument({ margin: 50 });

    return new Promise((resolve) => {
      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // Header
      doc.fontSize(20).text('Project Proposal', { align: 'center' });
      doc.moveDown();
      doc
        .fontSize(12)
        .text(`Reference: #${quote.id.slice(0, 8)}`, { align: 'right' });
      doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'right' });
      doc.moveDown(2);

      // Project Info
      doc.fontSize(16).text('Project Overview', { underline: true });
      doc.fontSize(12).text(`Service Type: ${quote.serviceType}`);
      doc.text(`Original Request: "${quote.description}"`);
      doc.text(`Client Budget: ${quote.budget}`);
      doc.moveDown();

      // Proposal Section
      doc.fontSize(16).text('Proposal Details', { underline: true });
      doc.moveDown();

      // Key Metrics
      doc.fontSize(12).text('Investment & Timeline', { underline: true });
      doc.text(`Estimated Cost: $${quote.proposal.price.toLocaleString()}`);
      doc.text(`Timeline: ${quote.proposal.estimatedDays} Days`);
      doc.text(`Valid Until: ${quote.proposal.validUntil}`);
      doc.moveDown();

      // Technical Approach
      doc.fontSize(12).text('Technical Approach', { underline: true });
      doc.fontSize(10).text(quote.proposal.content);
      doc.moveDown();

      // Milestones
      if (quote.proposal.milestones && quote.proposal.milestones.length > 0) {
        doc.fontSize(12).text('Execution Roadmap', { underline: true });
        doc.moveDown();

        let y = doc.y;
        quote.proposal.milestones.forEach((milestone, index) => {
          doc
            .fontSize(10)
            .text(`${index + 1}. ${milestone.title} (Week ${milestone.week})`);
          y += 15;
        });
      }

      // Footer
      doc
        .fontSize(10)
        .fillColor('grey')
        .text('Generated by Oftisoft AI Engine', 50, 700, { align: 'center' });

      doc.end();
    });
  }
}
